### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by shdudwns** [thebigsmileXD/PocketAI#3] opened 2017-12-18 03:46 UTC
[12:45:08] [Server thread/CRITICAL]: Could not tick level "world": Entity behaviour/properties file: entities/horse not found for entity of type Horse
[12:45:08] [Server thread/CRITICAL]: InvalidArgumentException: "Entity behaviour/properties file: entities/horse not found for entity of type Horse" (EXCEPTION) in "plugins/PocketAI-master/src/xenialdan/PocketAI/EntityProperties" at line 25
[12:45:08] [Server thread/DEBUG]: #0 plugins/PocketAI-master/src/xenialdan/PocketAI/entity/Horse(48): xenialdan\PocketAI\EntityProperties->__construct(string entities/horse, xenialdan\PocketAI\entity\Horse object)
[12:45:08] [Server thread/DEBUG]: #1 src/pocketmine/entity/Entity(539): xenialdan\PocketAI\entity\Horse->initEntity()
[12:45:08] [Server thread/DEBUG]: #2 src/pocketmine/entity/Entity(256): pocketmine\entity\Entity->__construct(pocketmine\level\Level object, pocketmine\nbt\tag\CompoundTag object)
[12:45:08] [Server thread/DEBUG]: #3 plugins/TeaSpoon-master/src/CortexPE/tile/MobSpawner(101): pocketmine\entity\Entity::createEntity(integer 23, pocketmine\level\Level object, pocketmine\nbt\tag\CompoundTag object)
[12:45:08] [Server thread/DEBUG]: #4 src/pocketmine/level/Level(763): CortexPE\tile\MobSpawner->onUpdate()
[12:45:08] [Server thread/DEBUG]: #5 src/pocketmine/Server(2377): pocketmine\level\Level->doTick(integer 961)
[12:45:08] [Server thread/DEBUG]: #6 src/pocketmine/Server(2534): pocketmine\Server->checkTickUpdates(integer 961, double 1513568708.9941)
[12:45:08] [Server thread/DEBUG]: #7 src/pocketmine/Server(2274): pocketmine\Server->tick()
[12:45:08] [Server thread/DEBUG]: #8 src/pocketmine/Server(2149): pocketmine\Server->tickProcessor()
[12:45:08] [Server thread/DEBUG]: #9 src/pocketmine/Server(1737): pocketmine\Server->start()
[12:45:08] [Server thread/DEBUG]: #10 src/pocketmine/PocketMine(554): pocketmine\Server->__construct(BaseClassLoader object, pocketmine\utils\MainLogger object, string /root/pm/, string /root/pm/plugins/)
[12:45:09] [Server thread/CRITICAL]: Coul

**Comment by inxomnyaa** [comment] 2017-12-18 20:10
Duplicate of #1 + #2

**Closed as completed by inxomnyaa** 2017-12-18 20:10 UTC
Labels: Duplicate, User/Usage issue, Did not read the README
